- hosts: localhost
  gather_facts: no
  tasks:
    - name: create job template and inventory
      include_role:
        name: job_template
      vars:
        inventories:
        - name: 'test'
        job_templates:
          - name: "Automated VM Template Creation"
            description: "Automated Creation of VMs that will be used as templates"
            job_type: "run"
            inventory:
               name: "test"
            project: "Automated VM Template Creation"
            become_enabled: "true"
            playbook: "configure_satellite.yml"
            execution_environment: ""
            limit: ""
            credentials:
              -  ""
            organization: ""
      