- hosts: localhost
  tasks:
  - name: create credential
    include_role:
        name: credentials
    run_once: true
  - name: create project
    include_role:
        name: projects
    run_once: true
  - name: create job template and inventory
    include_role:
        name: job_template  