- hosts: localhost
  gather_facts: no
  tasks:
  - name: Use CyberArk Lookup credential as password source
    ansible.controller.credential_input_source:
      input_field_name: password
      target_credential: root
      source_credential: cyberark_lookup
      metadata:
        object_query: "Safe=MY_SAFE;Object=awxuser"
        object_query_format: "Exact"
      state: present

  - name: create job template and inventory
    include_role:
        name: job_template
    vars:
        job_templates:
        - name: "Automated VM Template Creation"
          description: "Automated Creation of VMs that will be used as templates"
          job_type: "run"
          inventory:
              name: "test"
          project: 
              name: "Automated VM Template Creation"
          credentials:
          - name: "root"
            credential_type: "Machine"
            inputs:
                username: "root"
          become_enabled: "true"
          playbook: "configure_satellite.yml"
          execution_environment: ""
          limit: ""
          organization: ""

      