- hosts: localhost
  tasks:
  # lookup environment variables
  - name: lookup environment variables
    set_fact:
      awx_controller: "{{ lookup('env', 'CONTROLLER_HOST') | default(None) }}"

- hosts: "{{ awx_controller }}"
  tasks:
  - debug: var=awx_controller
  - name: create credential
    include_role:
        name: credential
  - name: create project
    include_role:
        name: project
  - name: create job template and inventory
    include_role:
        name: job_template  