- name: create credential type
  ansible.controller.credential_type:
    controller_oauth_token: "{{ item.controller_oauth_token | default(omit) }}"
    controller_username:    "{{ item.controller_username | default(omit) }}"
    controller_password:    "{{ item.controller_password | default(omit) }}"
    controller_host:        "{{ item.controller_host | default(omit) }}"
    validate_certs:         "{{ item.validate_certs | default(omit) }}"
    controller_config_file: "{{ item.controller_config_file | default(omit) }}"
    description:            "{{ item.description | default(omit) }}"
    inputs:                 "{{ item.inputs | default(omit) }}"
    kind:                   "{{ item.kind | default(omit) }}"
    name:                   "{{ item.name }}"
    request_timeout:        "{{ item.request_timeout | default(omit) }}"
    state:                  "{{ item.state | default('present') }}"
    injectors:              "{{ item.injectors | default(omit) }}"
    new_name:               "{{ item.new_name | default(omit) }}"
  with_items:               "{{ credential_types | default([]) }}"