- hosts: localhost
  vars_files:
  - ../vars/credential_types.yml
  tasks:
  - debug: 
      msg: "{{ credential_types }}"
  - name: create a custom credential
    include_role:
        name: credential_types 