- hosts: localhost
  tasks:
  - name: create credential
    include_role:
        name: credentials
  - name: create project
    include_role:
        name: projects
  - name: create job template and inventory
    include_role:
        name: job_template 